### ISSUE TITLE
[Question] What's the benefit of constant end-to-end latency?

### ISSUE THREAD

**Issue by quink-black** [Haivision/srt-rfc#101]
Here is what I thought about the constant end-to-end latency:
The cache management can be simplified for application. It's common for video player to have a cache after demuxer before decoder, so the player can control the time duration of cached data. However, cache at the transport layer can help packet loss recovery, and reduce head-of-line blocking.

What's the other benefit and use case of constant end-to-end latency? How about compare it to jitter buffer design/neteq in WebRTC?

**Comment by maxsharabayko** [comment]
> However, cache at the transport layer can help packet loss recovery, and reduce head-of-line blocking.

That's true. When the target end-to-end latency is known to a network protocol, it knows the time limits to try to recover a packet loss. And this logic can be tuned and developed in the protocol itself, instead of the demuxer+decoder app requesting retransmissions via some control protocol.

There is also a time drift between two machines. And demuxer is not always there to help.
Other things are jitter and packet reordering.
